language: generic
sudo : required
services:
  - docker
before_install:
  - docker build -t amitdocker/docker-react4 -f Dockerfile.dev .
script:
  - echo "skipping tests"
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Planetshare"
  env: "Planetshare-env"
  bucket_name: "elasticbeanstalk-ap-south-1-496046667163"
  bucket_path: "Planetshare"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
